services:
  server:
    volumes: !reset
      - server_logs:/app/logs
    depends_on: !reset
      mongo:
        condition: service_healthy
      postgres-migrate:
        condition: service_completed_successfully
